version: "3.9"

services:
    db:
        image: postgres
        restart: always
        container_name: db
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    api:
        build: ./api
        restart: always
        container_name: api
        ports:
            - 5000:5000
        depends_on:
            - db
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY}
            STRIPE_TEST_KEY: ${STRIPE_TEST_KEY}

    frontend:
        build: ./frontend
        restart: always
        container_name: frontend
        ports:
            - 8080:80
        profiles: ["frontend"]

    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 5001:8080
        profiles: ["adminer"]

volumes:
  db_data:
