version: "3"

services:
    db:
        image: postgres
        restart: always
        container_name: db
        networks:
            - network_prod
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    api:
        build: ../api
        restart: always
        container_name: api
        networks:
            - network_prod
        ports:
            - 5000:5000
        depends_on:
            - db
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY}
            STRIPE_TEST_KEY: ${STRIPE_TEST_KEY}

    reverse:
        image: nginx
        restart: always
        container_name: reverse
        networks:
            - network_prod
        volumes:
            - frontend_data:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api

    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 5001:8080

volumes:
  db_data:
  frontend_data:

networks:
    network_prod: